// Re-export all sidebar components for backwards compatibility
export { Sidebar } from "./sidebar";
export { SidebarContent } from "./sidebar-content";
export { SidebarFooter } from "./sidebar-footer";
export { SidebarGroup } from "./sidebar-group";
export { SidebarGroupAction } from "./sidebar-group-action";
export { SidebarGroupContent } from "./sidebar-group-content";
export { SidebarGroupLabel } from "./sidebar-group-label";
export { SidebarHeader } from "./sidebar-header";
export { SidebarInput } from "./sidebar-input";
export { SidebarInset } from "./sidebar-inset";
export { SidebarMenu } from "./sidebar-menu";
export { SidebarMenuAction } from "./sidebar-menu-action";
export { SidebarMenuBadge } from "./sidebar-menu-badge";
export { SidebarMenuButton } from "./sidebar-menu-button";
export { SidebarMenuItem } from "./sidebar-menu-item";
export { SidebarMenuSkeleton } from "./sidebar-menu-skeleton";
export { SidebarMenuSub } from "./sidebar-menu-sub";
export { SidebarMenuSubButton } from "./sidebar-menu-sub-button";
export { SidebarMenuSubItem } from "./sidebar-menu-sub-item";
export { SidebarProvider } from "./sidebar-provider";
export { SidebarRail } from "./sidebar-rail";
export { SidebarSeparator } from "./sidebar-separator";
export { SidebarTrigger } from "./sidebar-trigger";
export { useSidebar } from "./sidebar-context";
export type { SidebarProps } from "./sidebar";
export type { SidebarContentProps } from "./sidebar-content";
export type { SidebarFooterProps } from "./sidebar-footer";
export type { SidebarGroupProps } from "./sidebar-group";
export type { SidebarGroupActionProps } from "./sidebar-group-action";
export type { SidebarGroupContentProps } from "./sidebar-group-content";
export type { SidebarGroupLabelProps } from "./sidebar-group-label";
export type { SidebarHeaderProps } from "./sidebar-header";
export type { SidebarInputProps } from "./sidebar-input";
export type { SidebarInsetProps } from "./sidebar-inset";
export type { SidebarMenuProps } from "./sidebar-menu";
export type { SidebarMenuActionProps } from "./sidebar-menu-action";
export type { SidebarMenuBadgeProps } from "./sidebar-menu-badge";
export type { SidebarMenuButtonProps } from "./sidebar-menu-button";
export type { SidebarMenuItemProps } from "./sidebar-menu-item";
export type { SidebarMenuSkeletonProps } from "./sidebar-menu-skeleton";
export type { SidebarMenuSubProps } from "./sidebar-menu-sub";
export type { SidebarMenuSubButtonProps } from "./sidebar-menu-sub-button";
export type { SidebarMenuSubItemProps } from "./sidebar-menu-sub-item";
export type { SidebarProviderProps } from "./sidebar-provider";
export type { SidebarRailProps } from "./sidebar-rail";
export type { SidebarSeparatorProps } from "./sidebar-separator";
export type { SidebarTriggerProps } from "./sidebar-trigger";