/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as PreciosRouteImport } from './routes/precios'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as AvisoLegalRouteImport } from './routes/aviso-legal'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventosNuevoRouteImport } from './routes/eventos.nuevo'
import { Route as ArtistaSlugRouteImport } from './routes/artista.$slug'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedPanelRouteImport } from './routes/_authenticated/panel'

const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const PreciosRoute = PreciosRouteImport.update({
  id: '/precios',
  path: '/precios',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoLegalRoute = AvisoLegalRouteImport.update({
  id: '/aviso-legal',
  path: '/aviso-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosNuevoRoute = EventosNuevoRouteImport.update({
  id: '/nuevo',
  path: '/nuevo',
  getParentRoute: () => EventosRoute,
} as any)
const ArtistaSlugRoute = ArtistaSlugRouteImport.update({
  id: '/artista/$slug',
  path: '/artista/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPanelRoute = AuthenticatedPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/cookies': typeof CookiesRoute
  '/eventos': typeof EventosRouteWithChildren
  '/explorar': typeof ExplorarRoute
  '/login': typeof LoginRoute
  '/precios': typeof PreciosRoute
  '/privacidad': typeof PrivacidadRoute
  '/registro': typeof RegistroRoute
  '/terminos': typeof TerminosRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/artista/$slug': typeof ArtistaSlugRoute
  '/eventos/nuevo': typeof EventosNuevoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/cookies': typeof CookiesRoute
  '/eventos': typeof EventosRouteWithChildren
  '/explorar': typeof ExplorarRoute
  '/login': typeof LoginRoute
  '/precios': typeof PreciosRoute
  '/privacidad': typeof PrivacidadRoute
  '/registro': typeof RegistroRoute
  '/terminos': typeof TerminosRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/artista/$slug': typeof ArtistaSlugRoute
  '/eventos/nuevo': typeof EventosNuevoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/aviso-legal': typeof AvisoLegalRoute
  '/cookies': typeof CookiesRoute
  '/eventos': typeof EventosRouteWithChildren
  '/explorar': typeof ExplorarRoute
  '/login': typeof LoginRoute
  '/precios': typeof PreciosRoute
  '/privacidad': typeof PrivacidadRoute
  '/registro': typeof RegistroRoute
  '/terminos': typeof TerminosRoute
  '/_authenticated/panel': typeof AuthenticatedPanelRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/artista/$slug': typeof ArtistaSlugRoute
  '/eventos/nuevo': typeof EventosNuevoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aviso-legal'
    | '/cookies'
    | '/eventos'
    | '/explorar'
    | '/login'
    | '/precios'
    | '/privacidad'
    | '/registro'
    | '/terminos'
    | '/panel'
    | '/perfil'
    | '/artista/$slug'
    | '/eventos/nuevo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aviso-legal'
    | '/cookies'
    | '/eventos'
    | '/explorar'
    | '/login'
    | '/precios'
    | '/privacidad'
    | '/registro'
    | '/terminos'
    | '/panel'
    | '/perfil'
    | '/artista/$slug'
    | '/eventos/nuevo'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/aviso-legal'
    | '/cookies'
    | '/eventos'
    | '/explorar'
    | '/login'
    | '/precios'
    | '/privacidad'
    | '/registro'
    | '/terminos'
    | '/_authenticated/panel'
    | '/_authenticated/perfil'
    | '/artista/$slug'
    | '/eventos/nuevo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AvisoLegalRoute: typeof AvisoLegalRoute
  CookiesRoute: typeof CookiesRoute
  EventosRoute: typeof EventosRouteWithChildren
  ExplorarRoute: typeof ExplorarRoute
  LoginRoute: typeof LoginRoute
  PreciosRoute: typeof PreciosRoute
  PrivacidadRoute: typeof PrivacidadRoute
  RegistroRoute: typeof RegistroRoute
  TerminosRoute: typeof TerminosRoute
  ArtistaSlugRoute: typeof ArtistaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precios': {
      id: '/precios'
      path: '/precios'
      fullPath: '/precios'
      preLoaderRoute: typeof PreciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-legal': {
      id: '/aviso-legal'
      path: '/aviso-legal'
      fullPath: '/aviso-legal'
      preLoaderRoute: typeof AvisoLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/nuevo': {
      id: '/eventos/nuevo'
      path: '/nuevo'
      fullPath: '/eventos/nuevo'
      preLoaderRoute: typeof EventosNuevoRouteImport
      parentRoute: typeof EventosRoute
    }
    '/artista/$slug': {
      id: '/artista/$slug'
      path: '/artista/$slug'
      fullPath: '/artista/$slug'
      preLoaderRoute: typeof ArtistaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/panel': {
      id: '/_authenticated/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof AuthenticatedPanelRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedPanelRoute: typeof AuthenticatedPanelRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedPanelRoute: AuthenticatedPanelRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface EventosRouteChildren {
  EventosNuevoRoute: typeof EventosNuevoRoute
}

const EventosRouteChildren: EventosRouteChildren = {
  EventosNuevoRoute: EventosNuevoRoute,
}

const EventosRouteWithChildren =
  EventosRoute._addFileChildren(EventosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AvisoLegalRoute: AvisoLegalRoute,
  CookiesRoute: CookiesRoute,
  EventosRoute: EventosRouteWithChildren,
  ExplorarRoute: ExplorarRoute,
  LoginRoute: LoginRoute,
  PreciosRoute: PreciosRoute,
  PrivacidadRoute: PrivacidadRoute,
  RegistroRoute: RegistroRoute,
  TerminosRoute: TerminosRoute,
  ArtistaSlugRoute: ArtistaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
